language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION}

script: 
  - mkdir -p build/logs
  - php bin/phpunit -c phpunit.xml.dist

after_success:
  - travis_retry php bin/coveralls
  # or enable logging
  - travis_retry php bin/coveralls -v